// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLX8wS1OVs-t-QXT65zaVvnUonPpJQoFw',
    appId: '1:847410242176:android:5e87780a0f1e08687a7c65',
    messagingSenderId: '847410242176',
    projectId: 'thesis-dd3d3',
    storageBucket: 'thesis-dd3d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPzKhfvjLX1ntteeZ6Q4mSEp5oMV4L-RI',
    appId: '1:847410242176:ios:980edacc5dfb51397a7c65',
    messagingSenderId: '847410242176',
    projectId: 'thesis-dd3d3',
    storageBucket: 'thesis-dd3d3.firebasestorage.app',
    iosBundleId: 'com.hastorsd.thesisApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh4qX1nGB0fa1viQXg8YaefHFlhNDqFmE',
    appId: '1:847410242176:web:80b4b05b9d98dbb47a7c65',
    messagingSenderId: '847410242176',
    projectId: 'thesis-dd3d3',
    authDomain: 'thesis-dd3d3.firebaseapp.com',
    storageBucket: 'thesis-dd3d3.firebasestorage.app',
    measurementId: 'G-MZTH407S9W',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPzKhfvjLX1ntteeZ6Q4mSEp5oMV4L-RI',
    appId: '1:847410242176:ios:2a22b532e935194e7a7c65',
    messagingSenderId: '847410242176',
    projectId: 'thesis-dd3d3',
    storageBucket: 'thesis-dd3d3.firebasestorage.app',
    iosBundleId: 'com.example.thesisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh4qX1nGB0fa1viQXg8YaefHFlhNDqFmE',
    appId: '1:847410242176:web:1fd18b90e69707db7a7c65',
    messagingSenderId: '847410242176',
    projectId: 'thesis-dd3d3',
    authDomain: 'thesis-dd3d3.firebaseapp.com',
    storageBucket: 'thesis-dd3d3.firebasestorage.app',
    measurementId: 'G-8WMJZV9Y4Q',
  );

}